# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jekyll Gulp Boilerplate
email: krose@escaladesports.com
description: > # this means to ignore newlines until "baseurl:"
  Jekyll Gulp Boilerplate description
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
destination: ./docs
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - src
  - tasks
  - dev
  - config.js
  - server.js
  - gulpfile.js
  - package.json
  - node_modules
  - bower_components
  - README.md

compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all
